AllCops:
  Exclude:
    - 'app-ember/**/*'
    - 'bin/**/*'
    - 'config/routes.rb'
    - 'db/**/*'
    - 'Gemfile*'
    - 'tmp/**/*'
    - 'db/schema.rb'
LineLength:
  Max: 100
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
